global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi-model-server"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "host.docker.internal:30008"
          - "host.docker.internal:30007"
